# -*- coding: utf-8 -*-
"""Project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2JUIgjNu9uyKbsLW0xZBN7WzM0zKyeo
"""

import pandas as pd
import numpy as np

## Q1: Load the CSV file into a Pandas DataFrame."""
df = pd.read_csv('/content/banking_transactions.csv')
df

## Q2: Display the total number of customers in the dataset."""
df['CustomerID'].nunique()

## Q3: List all the unique cities where customers reside."""
df['City'].unique()

## Q4: What are the different types of accounts in the bank? Count the number of each."""
df.groupby('AccountType')['AccountType'].count()

## Q5: What is the average balance of all customers, grouped by Account Type?"""
df.groupby('AccountType')['Balance'].mean()

## Q6: Find the top 5 customers with the highest total transaction amounts."""
df.sort_values('TransactionAmount',ascending = False).head(5)

## Q7: How many total deposits, withdrawals, and transfers have been made? (TransactionType count)"""
df.groupby('TransactionType')['TransactionType'].count()

## Q8: What is the total deposited amount per branch? Sort in descending order."""
df_deposit = df[df['TransactionType']=='Deposit']
df_deposit_per_branch= df_deposit.groupby('BranchCode')['TransactionAmount'].sum()
df_deposit_per_branch

## Q9: Which gender has made the highest average transaction amount?"
df2 = df.groupby('Gender')['TransactionAmount'].mean()
df2
# max_amts = df2['TransactionAmount'].max()

## Q10: Find the customer(s) who made the highest single withdrawal."""
df_withdraw = df[df['TransactionType']=='Withdrawal']
max_amt = df_withdraw['TransactionAmount'].max()
df_withdraw[df_withdraw['TransactionAmount'] == max_amt]